### ISSUE TITLE
are 2 includes needed in overlay.rb?

### ISSUE THREAD

**Issue by ejaronne** [mitre/aws-rds-microsoft-sql-server-2014-instance-stig-baseline#2]
seeing the following line near the top and bottom of the overlay.rb file. isn't the second one at the bottom redundant?

include_controls 'microsoft-sql-server-2014-database-stig-baseline'

**Comment by asturtevant** [comment]
I added the second includes, as we have 2 microsoft sql stig profiles. 
1. microsoft-sql-server-2014-database-stig-baseline for the database, and
2. microsoft-sql-server-2014-instance-stig-baseline for the microsoft sql instance.

**Comment by aaronlippold** [comment]
I am getting some unexpected token errors with the includes

**Comment by ejaronne** [comment]
Looking at this, please rename to Instance, don't include or depend on database (since aws rds doesn't change anything for it), and update README accordingly. It should be very similar to the Instance base.
